"use client";

import { useState } from "react";

type ScriptResponse = {
  situation: string;
    regulate: string;
      connect: string;
        guide: string;
        };

        const EXAMPLES = [
          "My 4-year-old is screaming and hitting because I turned off the TV.",
            "My child is melting down because we have to leave the park.",
              "My son refuses bedtime and keeps kicking the wall.",
                "My daughter won't get dressed for school and is yelling at me.",
                ];

                function ScriptCard({ response }: { response: ScriptResponse }) {
                  return (
                      <div className="rounded-3xl border border-black/10 bg-white p-5 shadow-sm">
                            <div className="mb-4 flex items-center justify-between">
                                    <div>
                                              <p className="text-sm font-medium text-black/55">Sturdy response</p>
                                                        <h3 className="text-lg font-semibold text-neutral-900">
                                                                    Hard moment script
                                                                              </h3>
                                                                                      </div>
                                                                                              <div className="rounded-full bg-neutral-100 px-3 py-1 text-xs text-neutral-700">
                                                                                                        Live response
                                                                                                                </div>
                                                                                                                      </div>

                                                                                                                            <div className="rounded-2xl bg-neutral-50 p-4">
                                                                                                                                    <p className="text-xs font-semibold uppercase tracking-wide text-neutral-500">
                                                                                                                                              Situation
                                                                                                                                                      </p>
                                                                                                                                                              <p className="mt-2 text-sm leading-6 text-neutral-800">
                                                                                                                                                                        {response.situation}
                                                                                                                                                                                </p>
                                                                                                                                                                                      </div>

                                                                                                                                                                                            <div className="mt-4 space-y-3">
                                                                                                                                                                                                    <div className="rounded-2xl bg-[#F5F8FF] p-4">
                                                                                                                                                                                                              <p className="mb-1 text-sm font-semibold text-[#3157C7]">Regulate</p>
                                                                                                                                                                                                                        <p className="text-sm leading-6 text-neutral-800">
                                                                                                                                                                                                                                    {response.regulate}
                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                              <div className="rounded-2xl bg-[#F4FBF6] p-4">
                                                                                                                                                                                                                                                                        <p className="mb-1 text-sm font-semibold text-[#2F8A57]">Connect</p>
                                                                                                                                                                                                                                                                                  <p className="text-sm leading-6 text-neutral-800">
                                                                                                                                                                                                                                                                                              {response.connect}
                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                        <div className="rounded-2xl bg-[#FFF8EE] p-4">
                                                                                                                                                                                                                                                                                                                                  <p className="mb-1 text-sm font-semibold text-[#A56A00]">Guide</p>
                                                                                                                                                                                                                                                                                                                                            <p className="text-sm leading-6 text-neutral-800">{response.guide}</p>
                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                export default function ChatDemo() {
                                                                                                                                                                                                                                                                                                                                                                  const [message, setMessage] = useState(EXAMPLES[0]);
                                                                                                                                                                                                                                                                                                                                                                    const [response, setResponse] = useState<ScriptResponse | null>(null);
                                                                                                                                                                                                                                                                                                                                                                      const [error, setError] = useState("");
                                                                                                                                                                                                                                                                                                                                                                        const [isLoading, setIsLoading] = useState(false);

                                                                                                                                                                                                                                                                                                                                                                          async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
                                                                                                                                                                                                                                                                                                                                                                              e.preventDefault();

                                                                                                                                                                                                                                                                                                                                                                                  const trimmed = message.trim();
                                                                                                                                                                                                                                                                                                                                                                                      if (!trimmed) return;

                                                                                                                                                                                                                                                                                                                                                                                          setIsLoading(true);
                                                                                                                                                                                                                                                                                                                                                                                              setError("");

                                                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                                                        const res = await fetch("/api/chat-parenting-assistant", {
                                                                                                                                                                                                                                                                                                                                                                                                                method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                        headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                  "Content-Type": "application/json",
                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                  body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                            message: trimmed,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const data = await res.json();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!res.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              throw new Error(data?.error || "Something went wrong.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!data?.regulate || !data?.connect || !data?.guide) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  throw new Error("Response is missing required script fields.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setResponse({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      situation:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                data?.situation_summary ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "A hard parenting moment needs a calm, practical response.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  regulate: data.regulate,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          connect: data.connect,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  guide: data.guide,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const message =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          err instanceof Error ? err.message : "Something went wrong.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setError(message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setResponse(null);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setIsLoading(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="grid gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="rounded-3xl border border-black/10 bg-white p-4 shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mb-3 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-sm font-medium text-black/55">Try Sturdy</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="text-base font-semibold text-neutral-900">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          What’s happening right now?
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="rounded-full bg-neutral-100 px-3 py-1 text-xs text-neutral-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Chat-style input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <form onSubmit={handleSubmit} className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={message}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setMessage(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rows={4}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Describe the moment in one sentence."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="w-full resize-none rounded-2xl border border-black/10 bg-neutral-50 px-4 py-3 text-sm text-neutral-900 outline-none transition placeholder:text-neutral-400 focus:border-neutral-300"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex flex-wrap gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {EXAMPLES.map((example) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={example}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => setMessage(example)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="rounded-full bg-neutral-100 px-3 py-2 text-xs text-neutral-700 transition hover:bg-neutral-200"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {example.length > 42 ? `${example.slice(0, 42)}…` : example}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        disabled={isLoading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full rounded-2xl bg-neutral-900 px-4 py-3 text-sm font-semibold text-white transition hover:bg-neutral-800 disabled:cursor-not-allowed disabled:opacity-60"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {isLoading ? "Getting script..." : "Get script"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {error ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {error}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : null}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {isLoading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="rounded-3xl border border-black/10 bg-white p-5 shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-sm font-medium text-black/55">Sturdy response</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="mt-4 space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="h-20 animate-pulse rounded-2xl bg-neutral-100" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="h-20 animate-pulse rounded-2xl bg-neutral-100" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="h-20 animate-pulse rounded-2xl bg-neutral-100" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : null}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {response ? <ScriptCard response={response} /> : null}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }