"use client";

import { motion } from "framer-motion";

const fadeUp = {
  hidden: { opacity: 0, y: 20 },
    visible: (i: number) => ({
        opacity: 1,
            y: 0,
                transition: {
                      duration: 0.45,
                            delay: i * 0.12,
                          ease: "easeOut" as const,
                                      },
                                        }),
                                        };

                                        function StepCard({
                                          index,
                                            title,
                                              description,
                                                children,
                                                }: {
                                                  index: number;
                                                    title: string;
                                                      description: string;
                                                        children: React.ReactNode;
                                                        }) {
                                                          return (
                                                              <motion.div
                                                                    custom={index}
                                                                          initial="hidden"
                                                                                whileInView="visible"
                                                                                      viewport={{ once: true, amount: 0.3 }}
                                                                                            variants={fadeUp}
                                                                                                  className="rounded-3xl border border-black/10 bg-white p-6 shadow-sm"
                                                                                                      >
                                                                                                            <p className="text-sm font-medium text-black/50">Step {index + 1}</p>
                                                                                                                  <h3 className="mt-2 text-xl font-semibold text-neutral-900">{title}</h3>
                                                                                                                        <p className="mt-3 text-sm leading-6 text-neutral-600">{description}</p>
                                                                                                                              <div className="mt-5">{children}</div>
                                                                                                                                  </motion.div>
                                                                                                                                    );
                                                                                                                                    }

                                                                                                                                    export default function HowItWorksSection() {
                                                                                                                                      return (
                                                                                                                                          <section className="px-6 py-20 sm:px-8 lg:px-12">
                                                                                                                                                <div className="mx-auto max-w-6xl">
                                                                                                                                                        <div className="max-w-2xl">
                                                                                                                                                                  <h2 className="text-3xl font-semibold tracking-tight text-neutral-950 sm:text-4xl">
                                                                                                                                                                              Type the moment. Get the script.
                                                                                                                                                                                        </h2>
                                                                                                                                                                                                  <p className="mt-4 text-lg leading-8 text-neutral-700">
                                                                                                                                                                                                              Sturdy is built for high-stress parenting moments. It asks very
                                                                                                                                                                                                                          little, moves fast, and gives you words you can actually use.
                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                    <div className="mt-10 grid gap-6 lg:grid-cols-3">
                                                                                                                                                                                                                                                              <StepCard
                                                                                                                                                                                                                                                                          index={0}
                                                                                                                                                                                                                                                                                      title="Describe what’s happening"
                                                                                                                                                                                                                                                                                                  description="Parents use a simple chat-style input instead of searching, scrolling, or reading long advice."
                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                        <div className="rounded-2xl bg-neutral-50 p-4 text-sm text-neutral-800">
                                                                                                                                                                                                                                                                                                                                      “My child is screaming because we have to leave the park.”
                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                            </StepCard>

                                                                                                                                                                                                                                                                                                                                                                      <StepCard
                                                                                                                                                                                                                                                                                                                                                                                  index={1}
                                                                                                                                                                                                                                                                                                                                                                                              title="Sturdy reflects the real struggle"
                                                                                                                                                                                                                                                                                                                                                                                                          description="The response is grounded in the exact moment and shaped into three simple parts: Regulate, Connect, Guide."
                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="rounded-2xl bg-[#F5F8FF] p-3 text-sm text-neutral-800">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="mb-1 block font-semibold text-[#3157C7]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Regulate
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                You’re really upset about leaving.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="rounded-2xl bg-[#F4FBF6] p-3 text-sm text-neutral-800">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className="mb-1 block font-semibold text-[#2F8A57]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Connect
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              You wanted to stay longer, and that feels hard. I’m not going to
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              let you hit.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="rounded-2xl bg-[#FFF8EE] p-3 text-sm text-neutral-800">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="mb-1 block font-semibold text-[#A56A00]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Guide
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            We’re leaving now. You can hold my hand or I can help you get to
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            the car.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </StepCard>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <StepCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      index={2}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  title="Use it right away"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              description="The goal is not endless chat. The goal is a calm, firm, practical response you can say in the moment."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="rounded-2xl bg-neutral-900 p-4 text-sm leading-6 text-white">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  No judgment. No jargon. Just grounded words for what to say next.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </StepCard>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }