import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router }        from 'expo-router';
import { StatusBar }     from 'expo-status-bar';
import { SafeAreaView }  from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import { colors, spacing, type } from '../../src/theme';

export default function TermsScreen() {
  return (
    <View style={styles.root}>
      <StatusBar style="light" />
      <LinearGradient
        colors={[
          colors.gradientResultTop,
          colors.gradientResultMid1,
          colors.gradientResultMid2,
          colors.gradientResultMid3,
          colors.gradientMid4,
          colors.gradientBottom,
        ]}
        locations={[0, 0.10, 0.25, 0.42, 0.58, 1]}
        style={StyleSheet.absoluteFill}
      />
      <SafeAreaView style={styles.safe} edges={['top', 'bottom']}>
      <ScrollView contentContainerStyle={styles.content}>
        <Pressable
          onPress={() =>
            router.canGoBack()
              ? router.back()
              : router.replace('/(tabs)/account')
          }
          style={styles.back}
        >
          <Text style={styles.backText}>← Back</Text>
        </Pressable>

        <Text style={styles.title}>Terms of Service</Text>
        <Text style={styles.date}>Effective June 15, 2026</Text>

        <Text style={styles.body}>
          These Terms of Service govern your use of the Sturdy mobile
          application and related services. By creating an account or using
          Sturdy, you agree to these Terms.
        </Text>

        <Text style={styles.sectionTitle}>What Sturdy Is</Text>
        <Text style={styles.body}>
          Sturdy is a parenting support tool that uses artificial intelligence
          to generate communication scripts, suggestions, and answers to
          parenting questions. It helps parents navigate difficult moments by
          providing practical language they can use in real time.
          {'\n\n'}
          Sturdy is not a substitute for professional medical, psychological, or
          therapeutic services.
        </Text>

        <Text style={styles.sectionTitle}>Eligibility</Text>
        <Text style={styles.body}>
          You must be at least 18 years old to create an account. By using
          Sturdy, you represent that you are a parent or legal guardian seeking
          support for your own child or a child in your care.
        </Text>

        <Text style={styles.sectionTitle}>Accounts</Text>
        <Text style={styles.body}>
          You are responsible for maintaining the security of your account and
          for all activity under it. You may use Sturdy as a guest without an
          account — guest data is stored locally on your device and cannot be
          recovered if you uninstall the app. Create an account at any time to
          sync and back up your data.
        </Text>

        <Text style={styles.sectionTitle}>Free and Paid Plans</Text>
        <Text style={styles.body}>
          The free plan includes 75 script generations (SOS, Reconnect,
          Understand, and Conversation) and 25 questions per calendar month,
          tracked separately. Crisis support is always free and is never
          counted against either limit.
          {'\n\n'}
          Sturdy+ removes the monthly limit on all modes and unlocks additional
          features such as tone selection. Pricing is displayed on the upgrade
          screen and may change, but changes will not affect active subscription
          periods.
        </Text>

        <Text style={styles.sectionTitle}>Subscriptions and Billing</Text>
        <Text style={styles.body}>
          Sturdy+ subscriptions are billed through the Google Play Store or
          Apple App Store. Subscriptions automatically renew unless cancelled at
          least 24 hours before the renewal date. Manage or cancel your
          subscription through your store account settings.
          {'\n\n'}
          Free trials begin when you subscribe. If you do not cancel before the
          trial ends, you will be charged at the standard rate. Refunds are
          handled by the applicable store.
        </Text>

        <Text style={styles.sectionTitle}>Acceptable Use</Text>
        <Text style={styles.body}>
          You agree to use Sturdy only for parenting support. You agree not to
          use it for any unlawful purpose, attempt to exploit vulnerabilities,
          generate abusive or harmful content, misrepresent AI content as
          professional advice, or share your credentials with others.
          {'\n\n'}
          We may suspend or terminate your account if you violate these Terms.
        </Text>

        <Text style={styles.sectionTitle}>AI-Generated Content</Text>
        <Text style={styles.body}>
          All scripts and suggestions are generated by AI. They may sometimes be
          incomplete, inaccurate, or inappropriate for your situation. You are
          solely responsible for deciding whether and how to use any script
          provided.
          {'\n\n'}
          You retain ownership of the situations you describe. We retain
          ownership of AI-generated responses but grant you a personal,
          non-exclusive license to use them for your own parenting purposes.
        </Text>

        <Text style={styles.sectionTitle}>Crisis Situations</Text>
        <Text style={styles.body}>
          Sturdy includes a safety filter that detects potential crisis
          situations and displays emergency resources instead of generating a
          script. This system is not perfect and may not catch every emergency.
          {'\n\n'}
          Sturdy is not a crisis intervention service. If you or your child are
          in immediate danger, contact emergency services directly. Crisis
          features are always free regardless of your plan.
        </Text>

        <Text style={styles.sectionTitle}>Account Deletion</Text>
        <Text style={styles.body}>
          Delete your account at any time from Settings. Deletion permanently
          removes all your data and is irreversible. Cancel any active
          subscription through your store before deleting to avoid continued
          charges.
        </Text>

        <Text style={styles.sectionTitle}>Limitation of Liability</Text>
        <Text style={styles.body}>
          To the maximum extent permitted by law, Sturdy shall not be liable for
          any indirect, incidental, special, or consequential damages arising
          from your use of the Service. Our total liability shall not exceed the
          amount you paid for Sturdy+ in the preceding twelve months, or $50,
          whichever is greater.
        </Text>

        <Text style={styles.sectionTitle}>Disclaimer</Text>
        <Text style={styles.body}>
          The Service is provided "as is" without warranties of any kind. We do
          not warrant that it will be uninterrupted, error-free, or that
          AI-generated content will be accurate or suitable for any particular
          purpose.
        </Text>

        <Text style={styles.sectionTitle}>Changes to These Terms</Text>
        <Text style={styles.body}>
          We may update these Terms from time to time. Material changes will be
          communicated through the app or by email. Continued use constitutes
          acceptance.
          {'\n\n'}
          Questions? Contact us at sturdymobile@gmail.com.
        </Text>
      </ScrollView>
      </SafeAreaView>
    </View>
  );
}

const styles = StyleSheet.create({
  root:    { flex: 1, backgroundColor: colors.background },
  safe:    { flex: 1, backgroundColor: 'transparent' },
  content: {
    paddingHorizontal: spacing.lg,
    paddingTop:        spacing.md,
    paddingBottom:     spacing.xxl,
    gap:               spacing.md,
  },
  back:         { alignSelf: 'flex-start', paddingVertical: spacing.xs },
  backText:     { ...type.body, fontWeight: '600', color: colors.textSecondary },
  title:        { fontSize: 28, fontWeight: '800', color: colors.text, lineHeight: 34 },
  date:         { ...type.body, fontSize: 13, color: colors.textSecondary, opacity: 0.6 },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: colors.text, lineHeight: 24, marginTop: spacing.sm },
  body:         { ...type.body, color: colors.textSecondary, lineHeight: 28 },
});